name: run partial hydration pipeline
on:
  push:
    branches-ignore:
    - main
run-name: run-partial-hydration-pipeline
permissions: write-all

jobs:
  # check whether push to branch is associated with a PR
  check-if-pr-exists:
    runs-on: ubuntu-latest
    outputs:
      is-pr: ${{ steps.check_pr.outputs.is-pr }}  # Expose the result as a job output
    steps:
      - uses: actions/checkout@v4
      - name: Check if PR exists
        id: check_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(gh pr list --head ${{ github.ref_name }} --state open | wc -l)
          if [[ $pr_number -gt 0 ]]; then
            echo "is-pr=true" >> ${GITHUB_OUTPUT}
          else
            echo "is-pr=false" >> ${GITHUB_OUTPUT}
          fi

  # only invoke pipeline if push to branch is NOT associated to a PR
  hydration-pipline-partial:
    needs: [check-if-pr-exists]
    if: ${{ needs.check-if-pr-exists.outputs.is-pr == 'false' }} 
    uses: Enzyme3/demo-edge-hydration-workflows/.github/workflows/hydration_pipeline.yaml@main
    with:
      docker_credential_gcr_version: v2.1.22
      hydrator_image: us-docker.pkg.dev/kwpark1-test-123/mcd-tools/hydrator:latest
      run_full_pipeline: false
      service_account: github-wif@kwpark1-test-123.iam.gserviceaccount.com
      sot_validator_image: us-docker.pkg.dev/kwpark1-test-123/mcd-tools/csv-validator:latest
      used_workflow_ref: Enzyme3/demo-edge-hydration-workflows/.github/workflows/hydration_pipeline.yaml@main
      workload_identity_provider: projects/789864185540/locations/global/workloadIdentityPools/github-pool-a9134ad2/providers/github-pool-provider-a9134ad2
    secrets: inherit
